### ISSUE TITLE
add some pics to the language section

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/developer-note#15]

**Comment by tianhaoz95** [comment]
@all-contributors please add tianhaoz95 for question

**Comment by tianhaoz95** [comment]
@all-contributors please add tianhaoz95 for design

**Comment by tianhaoz95** [comment]
@all-contributors please add tianhaoz95 for design Code

**Comment by tianhaoz95** [comment]
@all-contributors please add tianhaoz95 for design infra

**Comment by tianhaoz95** [comment]
@all-contributors please add tianhaoz95 for design tutorial

**Comment by emzak208** [comment]
@all-contributors please add emzak208 for design

**Comment by tianhaoz95** [comment]
@all-contributors please add all-contributors for design

**Comment by tianhaoz95** [comment]
@all-contributors please add allcontributors for design

**Comment by tianhaoz95** [comment]
@all-contributors please remove all-contributors

**Comment by tianhaoz95** [comment]
@all-contributors please add jacksonz95 for design
